<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Chelsea Vu" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>SDS 348 Project 1- Crime in U.S. Cities</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">SDS 348 Project 1- Crime in U.S. Cities</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p>Chelsea Vu (clv743)</p>
<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p><span style="color:blue">. For this Project, I decided to look at the murder prevalence and demographic information of different U.S. cities. My first dataset, “murder_2016_prelim”, includes the number of murders in 2015, the number of murders in 2016 and the change in the number of murders between these two years for various U.S. cities. This dataset also includes the state of each city, the source from which each observation was obtained and the dates that the data are relevant up to. This data was obtained by various police departments and government websites. The second dataset I chose, “us.cities”, includes U.S. cities with a population greater than 40,000, their state, population, coordinates and whether they are a non-capitol city (0), a capitol city (1) or a state capitol(2).</span></p>
<p><span style="color:blue"> I am interested in observing what correlations might exist between the demographic information of these U.S. cities and their murder statistics. I expect that larger cities will have a larger number of murders but about the same percent change in murders as smaller cities. I also predict that capitol cities will have a greater proportion of murders</span>.</p>
<pre class="r"><code>r = getOption(&quot;repos&quot;)
r[&quot;CRAN&quot;] = &quot;http://cran.us.r-project.org&quot;
options(repos = r)
install.packages(&quot;dplyr&quot;)
library(dplyr)
install.packages(&quot;tidyr&quot;)
library(tidyr)

install.packages(&quot;fivethirtyeight&quot;)
library(fivethirtyeight)
data(murder_2016_prelim)

install.packages(&quot;maps&quot;)
library(maps)
data(us.cities)</code></pre>
</div>
<div id="tidying-rearranging-widelong" class="section level3">
<h3>Tidying: Rearranging Wide/long</h3>
<pre class="r"><code>untidy1 &lt;- murder_2016_prelim %&gt;% pivot_wider(names_from = &quot;state&quot;, 
    values_from = &quot;change&quot;)
head(untidy1)</code></pre>
<pre><code>## # A tibble: 6 x 39
##   city   murders_2015 murders_2016 source  as_of      Illinois Florida Tennessee
##   &lt;chr&gt;         &lt;int&gt;        &lt;int&gt; &lt;chr&gt;   &lt;date&gt;        &lt;int&gt;   &lt;int&gt;     &lt;int&gt;
## 1 Chica…          378          536 https:… 2016-10-02      158      NA        NA
## 2 Orlan…           19           73 OPD     2016-09-22       NA      54        NA
## 3 Memph…          114          158 MPD     2016-09-11       NA      NA        44
## 4 Phoen…           72          111 PPD     2016-08-31       NA      NA        NA
## 5 Las V…           90          125 http:/… 2016-09-28       NA      NA        NA
## 6 San A…           78          111 SAPD    2016-09-26       NA      NA        NA
## # … with 31 more variables: Arizona &lt;int&gt;, Nevada &lt;int&gt;, Texas &lt;int&gt;,
## #   Kentucky &lt;int&gt;, Indiana &lt;int&gt;, Georgia &lt;int&gt;, Missouri &lt;int&gt;,
## #   California &lt;int&gt;, New Mexico &lt;int&gt;, Oklahoma &lt;int&gt;, Nebraska &lt;int&gt;,
## #   Alaska &lt;int&gt;, New York &lt;int&gt;, Alabama &lt;int&gt;, North Carolina &lt;int&gt;,
## #   Michigan &lt;int&gt;, Pennsylvania &lt;int&gt;, Colorado &lt;int&gt;, New Jersey &lt;int&gt;,
## #   Ohio &lt;int&gt;, Massachusetts &lt;int&gt;, Louisiana &lt;int&gt;, Washington &lt;int&gt;,
## #   Hawaii &lt;int&gt;, Kansas &lt;int&gt;, Virginia &lt;int&gt;, Oregon &lt;int&gt;, Minnesota &lt;int&gt;,
## #   D.C. &lt;int&gt;, Maryland &lt;int&gt;, Wisconsin &lt;int&gt;</code></pre>
<pre class="r"><code>tidy1 &lt;- untidy1 %&gt;% pivot_longer(6:39, names_to = &quot;state&quot;, values_to = &quot;change&quot;) %&gt;% 
    na.omit()
head(tidy1)</code></pre>
<pre><code>## # A tibble: 6 x 7
##   city    murders_2015 murders_2016 source               as_of      state change
##   &lt;chr&gt;          &lt;int&gt;        &lt;int&gt; &lt;chr&gt;                &lt;date&gt;     &lt;chr&gt;  &lt;int&gt;
## 1 Chicago          378          536 https://portal.chic… 2016-10-02 Illi…    158
## 2 Orlando           19           73 OPD                  2016-09-22 Flor…     54
## 3 Memphis          114          158 MPD                  2016-09-11 Tenn…     44
## 4 Phoenix           72          111 PPD                  2016-08-31 Ariz…     39
## 5 Las Ve…           90          125 http://www.lvmpd.co… 2016-09-28 Neva…     35
## 6 San An…           78          111 SAPD                 2016-09-26 Texas     33</code></pre>
<p><span style="color:blue">The “untidy1” dataset is the untidy version of the “murder_2016_prelim” dataset, created by using “pivot_wider”. This was made tidy again by using the “pivot_longer” function on “untidy1” and creating the “tidy1” dataset, which is the same as the “murder_2016_prelim” dataset.</span></p>
<pre class="r"><code>untidy2 &lt;- us.cities %&gt;% pivot_wider(names_from = &quot;country.etc&quot;, 
    values_from = &quot;capital&quot;)
head(untidy2)</code></pre>
<pre><code>## # A tibble: 6 x 55
##   name          pop   lat   long    TX    OH    CA    GA    NY    OR    NM    LA
##   &lt;chr&gt;       &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 Abilene TX 113888  32.4  -99.7     0    NA    NA    NA    NA    NA    NA    NA
## 2 Akron OH   206634  41.1  -81.5    NA     0    NA    NA    NA    NA    NA    NA
## 3 Alameda CA  70069  37.8 -122.     NA    NA     0    NA    NA    NA    NA    NA
## 4 Albany GA   75510  31.6  -84.2    NA    NA    NA     0    NA    NA    NA    NA
## 5 Albany NY   93576  42.7  -73.8    NA    NA    NA    NA     2    NA    NA    NA
## 6 Albany OR   45535  44.6 -123.     NA    NA    NA    NA    NA     0    NA    NA
## # … with 43 more variables: VA &lt;int&gt;, PA &lt;int&gt;, FL &lt;int&gt;, IA &lt;int&gt;, AK &lt;int&gt;,
## #   IN &lt;int&gt;, MA &lt;int&gt;, MI &lt;int&gt;, MD &lt;int&gt;, MN &lt;int&gt;, WI &lt;int&gt;, IL &lt;int&gt;,
## #   CO &lt;int&gt;, NC &lt;int&gt;, NJ &lt;int&gt;, AL &lt;int&gt;, WA &lt;int&gt;, ME &lt;int&gt;, AZ &lt;int&gt;,
## #   TN &lt;int&gt;, NE &lt;int&gt;, MT &lt;int&gt;, MS &lt;int&gt;, ND &lt;int&gt;, MO &lt;int&gt;, ID &lt;int&gt;,
## #   UT &lt;int&gt;, KY &lt;int&gt;, CT &lt;int&gt;, OK &lt;int&gt;, NV &lt;int&gt;, WY &lt;int&gt;, SC &lt;int&gt;,
## #   WV &lt;int&gt;, NH &lt;int&gt;, AR &lt;int&gt;, RI &lt;int&gt;, DE &lt;int&gt;, HI &lt;int&gt;, KS &lt;int&gt;,
## #   VT &lt;int&gt;, SD &lt;int&gt;, DC &lt;int&gt;</code></pre>
<pre class="r"><code>tidy2 &lt;- untidy2 %&gt;% pivot_longer(5:55, names_to = &quot;country.etc&quot;, 
    values_to = &quot;capital&quot;) %&gt;% na.omit()
head(tidy2)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   name          pop   lat   long country.etc capital
##   &lt;chr&gt;       &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;         &lt;int&gt;
## 1 Abilene TX 113888  32.4  -99.7 TX                0
## 2 Akron OH   206634  41.1  -81.5 OH                0
## 3 Alameda CA  70069  37.8 -122.  CA                0
## 4 Albany GA   75510  31.6  -84.2 GA                0
## 5 Albany NY   93576  42.7  -73.8 NY                2
## 6 Albany OR   45535  44.6 -123.  OR                0</code></pre>
<p><span style="color:blue">The “us.cities” dataset was made untidy by using “pivot_wider”, and this untidy version is called “untidy2”. This was made tidy again by using “pivot_longer” on “untidy2”, leaving the “tidy2” dataset, which is the same as the original “us.cities” dataset. </span></p>
</div>
<div id="joiningmerging" class="section level3">
<h3>Joining/Merging</h3>
<pre class="r"><code>newus.cities &lt;- us.cities %&gt;% separate(name, into = c(&quot;city&quot;, 
    &quot;state&quot;)) %&gt;% glimpse</code></pre>
<pre><code>## Rows: 1,005
## Columns: 7
## $ city        &lt;chr&gt; &quot;Abilene&quot;, &quot;Akron&quot;, &quot;Alameda&quot;, &quot;Albany&quot;, &quot;Albany&quot;, &quot;Albany…
## $ state       &lt;chr&gt; &quot;TX&quot;, &quot;OH&quot;, &quot;CA&quot;, &quot;GA&quot;, &quot;NY&quot;, &quot;OR&quot;, &quot;NM&quot;, &quot;LA&quot;, &quot;VA&quot;, &quot;CA&quot;…
## $ country.etc &lt;chr&gt; &quot;TX&quot;, &quot;OH&quot;, &quot;CA&quot;, &quot;GA&quot;, &quot;NY&quot;, &quot;OR&quot;, &quot;NM&quot;, &quot;LA&quot;, &quot;VA&quot;, &quot;CA&quot;…
## $ pop         &lt;int&gt; 113888, 206634, 70069, 75510, 93576, 45535, 494962, 44933,…
## $ lat         &lt;dbl&gt; 32.45, 41.08, 37.77, 31.58, 42.67, 44.62, 35.12, 31.29, 38…
## $ long        &lt;dbl&gt; -99.74, -81.52, -122.26, -84.18, -73.80, -123.09, -106.62,…
## $ capital     &lt;int&gt; 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
<pre class="r"><code>newjoin &lt;- full_join(newus.cities, murder_2016_prelim, by = c(&quot;city&quot;)) %&gt;% 
    na.omit() %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 71
## Columns: 13
## $ city         &lt;chr&gt; &quot;Albuquerque&quot;, &quot;Anaheim&quot;, &quot;Anchorage&quot;, &quot;Arlington&quot;, &quot;Arli…
## $ state.x      &lt;chr&gt; &quot;NM&quot;, &quot;CA&quot;, &quot;AK&quot;, &quot;Heights&quot;, &quot;MA&quot;, &quot;TX&quot;, &quot;VA&quot;, &quot;GA&quot;, &quot;CO&quot;…
## $ country.etc  &lt;chr&gt; &quot;NM&quot;, &quot;CA&quot;, &quot;AK&quot;, &quot;IL&quot;, &quot;MA&quot;, &quot;TX&quot;, &quot;VA&quot;, &quot;GA&quot;, &quot;CO&quot;, &quot;IL…
## $ pop          &lt;int&gt; 494962, 334909, 279428, 74763, 41246, 374729, 184603, 424…
## $ lat          &lt;dbl&gt; 35.12, 33.84, 61.18, 42.09, 42.42, 32.69, 38.88, 33.76, 3…
## $ long         &lt;dbl&gt; -106.62, -117.87, -149.19, -87.98, -71.16, -97.13, -77.10…
## $ capital      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, …
## $ state.y      &lt;chr&gt; &quot;New Mexico&quot;, &quot;California&quot;, &quot;Alaska&quot;, &quot;Texas&quot;, &quot;Texas&quot;, &quot;…
## $ murders_2015 &lt;int&gt; 35, 10, 19, 4, 4, 4, 4, 68, 13, 13, 13, 21, 249, 28, 31, …
## $ murders_2016 &lt;int&gt; 46, 4, 26, 17, 17, 17, 17, 85, 16, 16, 28, 22, 230, 28, 3…
## $ change       &lt;int&gt; 11, -6, 7, 13, 13, 13, 13, 17, 3, 3, 15, 1, -19, 0, 7, 7,…
## $ source       &lt;chr&gt; &quot;APD&quot;, &quot;APD&quot;, &quot;APD&quot;, &quot;http://www.arlington-tx.gov/police/…
## $ as_of        &lt;date&gt; 2016-09-21, 2016-06-27, 2016-09-27, 2016-08-31, 2016-08-…</code></pre>
<p><span style="color:blue">I joined the two datasets based on the common variable of “city”. To join these two datasets, I had to modify “city” ID variable of the “us.cities” dataset so that it included only the city in the name and not the state. I did this by using the “separate” function, and the resulting dataset was called “newus.cities”. This dataset had 1005 observations and 7 variables. The unchanged “murder_2016_prelim” had 79 observations and 7 variables. Finally, I joined the “newus.cities” and the “murder_2016_prelim” datasets using the “full_join” function and the common ID variable, “city”. To remove the cities that only appeared in one of the two datasets, I used “na.omit()” to remove rows containing NAs. I decided to use a full join to preserve all of the variables from both datasets. This final, combined dataset, called “newjoin”, has 13 variables and 71 observations. </span></p>
</div>
<div id="wrangling" class="section level3">
<h3>Wrangling</h3>
<pre class="r"><code>newjoin %&gt;% filter(country.etc == &quot;TX&quot;) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 7
## Columns: 13
## $ city         &lt;chr&gt; &quot;Arlington&quot;, &quot;Austin&quot;, &quot;Dallas&quot;, &quot;Houston&quot;, &quot;Laredo&quot;, &quot;Pl…
## $ state.x      &lt;chr&gt; &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;Falls&quot;
## $ country.etc  &lt;chr&gt; &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;
## $ pop          &lt;int&gt; 374729, 683404, 1216543, 2043005, 218041, 260415, 100616
## $ lat          &lt;dbl&gt; 32.69, 30.31, 32.79, 29.77, 27.53, 33.05, 33.90
## $ long         &lt;dbl&gt; -97.13, -97.75, -96.77, -95.39, -99.49, -96.75, -98.52
## $ capital      &lt;int&gt; 0, 2, 0, 0, 0, 0, 0
## $ state.y      &lt;chr&gt; &quot;Texas&quot;, &quot;Texas&quot;, &quot;Texas&quot;, &quot;Texas&quot;, &quot;Texas&quot;, &quot;Texas&quot;, &quot;Ka…
## $ murders_2015 &lt;int&gt; 4, 13, 95, 191, 7, 2, 13
## $ murders_2016 &lt;int&gt; 17, 28, 118, 212, 9, 5, 10
## $ change       &lt;int&gt; 13, 15, 23, 21, 2, 3, -3
## $ source       &lt;chr&gt; &quot;http://www.arlington-tx.gov/police/wp-content/uploads/si…
## $ as_of        &lt;date&gt; 2016-08-31, 2016-08-31, 2016-08-31, 2016-08-31, 2016-09-2…</code></pre>
<pre class="r"><code>newjoin1 &lt;- newjoin %&gt;% select(-state.x, -state.y, -source, -as_of, 
    -lat, -long) %&gt;% rename(state = country.etc) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 71
## Columns: 7
## $ city         &lt;chr&gt; &quot;Albuquerque&quot;, &quot;Anaheim&quot;, &quot;Anchorage&quot;, &quot;Arlington&quot;, &quot;Arli…
## $ state        &lt;chr&gt; &quot;NM&quot;, &quot;CA&quot;, &quot;AK&quot;, &quot;IL&quot;, &quot;MA&quot;, &quot;TX&quot;, &quot;VA&quot;, &quot;GA&quot;, &quot;CO&quot;, &quot;IL…
## $ pop          &lt;int&gt; 494962, 334909, 279428, 74763, 41246, 374729, 184603, 424…
## $ capital      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, …
## $ murders_2015 &lt;int&gt; 35, 10, 19, 4, 4, 4, 4, 68, 13, 13, 13, 21, 249, 28, 31, …
## $ murders_2016 &lt;int&gt; 46, 4, 26, 17, 17, 17, 17, 85, 16, 16, 28, 22, 230, 28, 3…
## $ change       &lt;int&gt; 11, -6, 7, 13, 13, 13, 13, 17, 3, 3, 15, 1, -19, 0, 7, 7,…</code></pre>
<pre class="r"><code>newjoin1$capital[newjoin1$capital == 0] &lt;- &quot;Non-capital&quot;
newjoin1$capital[newjoin1$capital == 1] &lt;- &quot;Capital&quot;
newjoin1$capital[newjoin1$capital == 2] &lt;- &quot;State-capital&quot;



newjoin1 %&gt;% arrange(desc(murders_2015))</code></pre>
<pre><code>##            city state     pop       capital murders_2015 murders_2016 change
## 1       Chicago    IL 2830144   Non-capital          378          536    158
## 2     Baltimore    MD  602658   Non-capital          249          230    -19
## 3       Detroit    MI  871789   Non-capital          216          221      5
## 4  Philadelphia    PA 1439814   Non-capital          209          213      4
## 5       Houston    TX 2043005   Non-capital          191          212     21
## 6       Memphis    TN  639736   Non-capital          114          158     44
## 7     Milwaukee    WI  575250   Non-capital          105           84    -21
## 8  Indianapolis    IN  771725 State-capital          102          117     15
## 9     Cleveland    OH   47123   Non-capital           96           89     -7
## 10    Cleveland    OH  443949   Non-capital           96           89     -7
## 11       Dallas    TX 1216543   Non-capital           95          118     23
## 12       Newark    CA   43018   Non-capital           76           72     -4
## 13       Newark    NJ  281378   Non-capital           76           72     -4
## 14       Newark    OH   46870   Non-capital           76           72     -4
##  [ reached &#39;max&#39; / getOption(&quot;max.print&quot;) -- omitted 57 rows ]</code></pre>
<pre class="r"><code>newjoin1 %&gt;% group_by(state) %&gt;% summarize(mean_murders2015 = mean(murders_2015, 
    na.rm = T)) %&gt;% arrange(desc(mean_murders2015))</code></pre>
<pre><code>## # A tibble: 32 x 2
##    state mean_murders2015
##    &lt;chr&gt;            &lt;dbl&gt;
##  1 MD               249  
##  2 MI               216  
##  3 PA               128. 
##  4 IL               106. 
##  5 WI               105  
##  6 IN                86.5
##  7 TN                80.5
##  8 NJ                76  
##  9 GA                69.5
## 10 OH                65.7
## # … with 22 more rows</code></pre>
<pre class="r"><code>newjoin1 %&gt;% group_by(state) %&gt;% summarize(mean_murders2016 = mean(murders_2016, 
    na.rm = T)) %&gt;% arrange(desc(mean_murders2016))</code></pre>
<pre><code>## # A tibble: 32 x 2
##    state mean_murders2016
##    &lt;chr&gt;            &lt;dbl&gt;
##  1 MD               230  
##  2 MI               221  
##  3 IL               152. 
##  4 PA               130. 
##  5 TN               104. 
##  6 IN                93.5
##  7 WI                84  
##  8 GA                77.5
##  9 NJ                72  
## 10 OH                63  
## # … with 22 more rows</code></pre>
<pre class="r"><code>newjoin1 %&gt;% group_by(state) %&gt;% summarize(mean_pop = mean(pop, 
    na.rm = T)) %&gt;% arrange(desc(mean_pop))</code></pre>
<pre><code>## # A tibble: 32 x 2
##    state mean_pop
##    &lt;chr&gt;    &lt;dbl&gt;
##  1 PA     878043 
##  2 MI     871789 
##  3 IL     782346.
##  4 AZ     741356.
##  5 TX     699536.
##  6 MD     602658 
##  7 TN     581642.
##  8 WI     575250 
##  9 OR     542751 
## 10 NM     494962 
## # … with 22 more rows</code></pre>
<pre class="r"><code>newjoin2 &lt;- newjoin1 %&gt;% mutate(murders2015_per_pop = murders_2015/pop) %&gt;% 
    mutate(murders2016_per_pop = murders_2016/pop) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 71
## Columns: 9
## $ city                &lt;chr&gt; &quot;Albuquerque&quot;, &quot;Anaheim&quot;, &quot;Anchorage&quot;, &quot;Arlington&quot;…
## $ state               &lt;chr&gt; &quot;NM&quot;, &quot;CA&quot;, &quot;AK&quot;, &quot;IL&quot;, &quot;MA&quot;, &quot;TX&quot;, &quot;VA&quot;, &quot;GA&quot;, &quot;C…
## $ pop                 &lt;int&gt; 494962, 334909, 279428, 74763, 41246, 374729, 1846…
## $ capital             &lt;chr&gt; &quot;Non-capital&quot;, &quot;Non-capital&quot;, &quot;Non-capital&quot;, &quot;Non-…
## $ murders_2015        &lt;int&gt; 35, 10, 19, 4, 4, 4, 4, 68, 13, 13, 13, 21, 249, 2…
## $ murders_2016        &lt;int&gt; 46, 4, 26, 17, 17, 17, 17, 85, 16, 16, 28, 22, 230…
## $ change              &lt;int&gt; 11, -6, 7, 13, 13, 13, 13, 17, 3, 3, 15, 1, -19, 0…
## $ murders2015_per_pop &lt;dbl&gt; 7.071250e-05, 2.985886e-05, 6.799605e-05, 5.350240…
## $ murders2016_per_pop &lt;dbl&gt; 9.293643e-05, 1.194354e-05, 9.304723e-05, 2.273852…</code></pre>
<pre class="r"><code>newjoin2$capital[newjoin2$capital == 0] &lt;- &quot;Non-capital&quot;
newjoin2$capital[newjoin2$capital == 1] &lt;- &quot;Capital&quot;
newjoin2$capital[newjoin2$capital == 2] &lt;- &quot;State-capital&quot;

newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_2015murders_per_pop = mean(murders2015_per_pop, 
    na.rm = T)) %&gt;% arrange(desc(mean_2015murders_per_pop)) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Rows: 32
## Columns: 2
## $ state                    &lt;chr&gt; &quot;IN&quot;, &quot;OH&quot;, &quot;MD&quot;, &quot;ME&quot;, &quot;NC&quot;, &quot;GA&quot;, &quot;NJ&quot;, &quot;FL…
## $ mean_2015murders_per_pop &lt;dbl&gt; 9.658905e-04, 6.921466e-04, 4.131697e-04, 3.0…</code></pre>
<pre class="r"><code>library(&quot;knitr&quot;)

kable(summary(newjoin2, type = &quot;numeric&quot;))</code></pre>
<table>
<colgroup>
<col width="1%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">city</th>
<th align="left">state</th>
<th align="left">pop</th>
<th align="left">capital</th>
<th align="left">murders_2015</th>
<th align="left">murders_2016</th>
<th align="left">change</th>
<th align="left">murders2015_per_pop</th>
<th align="left">murders2016_per_pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">Length:71</td>
<td align="left">Length:71</td>
<td align="left">Min. : 39453</td>
<td align="left">Length:71</td>
<td align="left">Min. : 0.00</td>
<td align="left">Min. : 3.00</td>
<td align="left">Min. :-21.000</td>
<td align="left">Min. :0.000e+00</td>
<td align="left">Min. :1.174e-05</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Class :character</td>
<td align="left">Class :character</td>
<td align="left">1st Qu.: 209826</td>
<td align="left">Class :character</td>
<td align="left">1st Qu.: 13.00</td>
<td align="left">1st Qu.: 15.00</td>
<td align="left">1st Qu.: -3.500</td>
<td align="left">1st Qu.:3.959e-05</td>
<td align="left">1st Qu.:4.662e-05</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Mode :character</td>
<td align="left">Mode :character</td>
<td align="left">Median : 306351</td>
<td align="left">Mode :character</td>
<td align="left">Median : 31.00</td>
<td align="left">Median : 30.00</td>
<td align="left">Median : 2.000</td>
<td align="left">Median :8.977e-05</td>
<td align="left">Median :9.700e-05</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">Mean : 434814</td>
<td align="left">NA</td>
<td align="left">Mean : 51.49</td>
<td align="left">Mean : 57.24</td>
<td align="left">Mean : 5.746</td>
<td align="left">Mean :2.279e-04</td>
<td align="left">Mean :2.428e-04</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">3rd Qu.: 524408</td>
<td align="left">NA</td>
<td align="left">3rd Qu.: 69.50</td>
<td align="left">3rd Qu.: 72.00</td>
<td align="left">3rd Qu.: 9.000</td>
<td align="left">3rd Qu.:1.655e-04</td>
<td align="left">3rd Qu.:2.216e-04</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">Max. :2830144</td>
<td align="left">NA</td>
<td align="left">Max. :378.00</td>
<td align="left">Max. :536.00</td>
<td align="left">Max. :158.000</td>
<td align="left">Max. :2.037e-03</td>
<td align="left">Max. :1.889e-03</td>
</tr>
</tbody>
</table>
<pre class="r"><code>newjoin2 %&gt;% summarize(mean_pop = mean(pop, na.rm = T), sd_pop = sd(pop), 
    var_pop = var(pop), quantile_pop = quantile(pop), min_pop = min(pop), 
    max_pop = max(pop), n_rows = n(), n_dist_pop = n_distinct(pop)) %&gt;% 
    kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">mean_pop</th>
<th align="right">sd_pop</th>
<th align="right">var_pop</th>
<th align="right">quantile_pop</th>
<th align="right">min_pop</th>
<th align="right">max_pop</th>
<th align="right">n_rows</th>
<th align="right">n_dist_pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">434814.3</td>
<td align="right">454871</td>
<td align="right">206907614668</td>
<td align="right">39453.0</td>
<td align="right">39453</td>
<td align="right">2830144</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="even">
<td align="right">434814.3</td>
<td align="right">454871</td>
<td align="right">206907614668</td>
<td align="right">209826.0</td>
<td align="right">39453</td>
<td align="right">2830144</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="odd">
<td align="right">434814.3</td>
<td align="right">454871</td>
<td align="right">206907614668</td>
<td align="right">306351.0</td>
<td align="right">39453</td>
<td align="right">2830144</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="even">
<td align="right">434814.3</td>
<td align="right">454871</td>
<td align="right">206907614668</td>
<td align="right">524407.5</td>
<td align="right">39453</td>
<td align="right">2830144</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="odd">
<td align="right">434814.3</td>
<td align="right">454871</td>
<td align="right">206907614668</td>
<td align="right">2830144.0</td>
<td align="right">39453</td>
<td align="right">2830144</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
</tbody>
</table>
<pre class="r"><code>newjoin2 %&gt;% summarize(mean_murders2015 = mean(murders_2015, 
    na.rm = T), sd_muders2015 = sd(murders_2015), var_murders2015 = var(murders_2015), 
    quantile_murders2015 = quantile(murders_2015), min_murders2015 = min(murders_2015), 
    max_murders2015 = max(murders_2015), n_rows = n(), n_dist_murders2015 = n_distinct(murders_2015)) %&gt;% 
    kable()</code></pre>
<table>
<colgroup>
<col width="13%" />
<col width="11%" />
<col width="12%" />
<col width="16%" />
<col width="12%" />
<col width="12%" />
<col width="5%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">mean_murders2015</th>
<th align="right">sd_muders2015</th>
<th align="right">var_murders2015</th>
<th align="right">quantile_murders2015</th>
<th align="right">min_murders2015</th>
<th align="right">max_murders2015</th>
<th align="right">n_rows</th>
<th align="right">n_dist_murders2015</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">51.49296</td>
<td align="right">64.94676</td>
<td align="right">4218.082</td>
<td align="right">0.0</td>
<td align="right">0</td>
<td align="right">378</td>
<td align="right">71</td>
<td align="right">45</td>
</tr>
<tr class="even">
<td align="right">51.49296</td>
<td align="right">64.94676</td>
<td align="right">4218.082</td>
<td align="right">13.0</td>
<td align="right">0</td>
<td align="right">378</td>
<td align="right">71</td>
<td align="right">45</td>
</tr>
<tr class="odd">
<td align="right">51.49296</td>
<td align="right">64.94676</td>
<td align="right">4218.082</td>
<td align="right">31.0</td>
<td align="right">0</td>
<td align="right">378</td>
<td align="right">71</td>
<td align="right">45</td>
</tr>
<tr class="even">
<td align="right">51.49296</td>
<td align="right">64.94676</td>
<td align="right">4218.082</td>
<td align="right">69.5</td>
<td align="right">0</td>
<td align="right">378</td>
<td align="right">71</td>
<td align="right">45</td>
</tr>
<tr class="odd">
<td align="right">51.49296</td>
<td align="right">64.94676</td>
<td align="right">4218.082</td>
<td align="right">378.0</td>
<td align="right">0</td>
<td align="right">378</td>
<td align="right">71</td>
<td align="right">45</td>
</tr>
</tbody>
</table>
<pre class="r"><code>newjoin2 %&gt;% summarize(mean_murders2016 = mean(murders_2016, 
    na.rm = T), sd_muders2016 = sd(murders_2016), var_murders2016 = var(murders_2016), 
    quantile_murders2016 = quantile(murders_2016), min_murders2016 = min(murders_2016), 
    max_murders2016 = max(murders_2016), n_rows = n(), n_dist_murders2016 = n_distinct(murders_2016)) %&gt;% 
    kable()</code></pre>
<table>
<colgroup>
<col width="13%" />
<col width="11%" />
<col width="12%" />
<col width="16%" />
<col width="12%" />
<col width="12%" />
<col width="5%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">mean_murders2016</th>
<th align="right">sd_muders2016</th>
<th align="right">var_murders2016</th>
<th align="right">quantile_murders2016</th>
<th align="right">min_murders2016</th>
<th align="right">max_murders2016</th>
<th align="right">n_rows</th>
<th align="right">n_dist_murders2016</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">57.23944</td>
<td align="right">78.338</td>
<td align="right">6136.842</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">536</td>
<td align="right">71</td>
<td align="right">43</td>
</tr>
<tr class="even">
<td align="right">57.23944</td>
<td align="right">78.338</td>
<td align="right">6136.842</td>
<td align="right">15</td>
<td align="right">3</td>
<td align="right">536</td>
<td align="right">71</td>
<td align="right">43</td>
</tr>
<tr class="odd">
<td align="right">57.23944</td>
<td align="right">78.338</td>
<td align="right">6136.842</td>
<td align="right">30</td>
<td align="right">3</td>
<td align="right">536</td>
<td align="right">71</td>
<td align="right">43</td>
</tr>
<tr class="even">
<td align="right">57.23944</td>
<td align="right">78.338</td>
<td align="right">6136.842</td>
<td align="right">72</td>
<td align="right">3</td>
<td align="right">536</td>
<td align="right">71</td>
<td align="right">43</td>
</tr>
<tr class="odd">
<td align="right">57.23944</td>
<td align="right">78.338</td>
<td align="right">6136.842</td>
<td align="right">536</td>
<td align="right">3</td>
<td align="right">536</td>
<td align="right">71</td>
<td align="right">43</td>
</tr>
</tbody>
</table>
<pre class="r"><code>newjoin2 %&gt;% summarize(mean_change = mean(change, na.rm = T), 
    sd_change = sd(change), var_change = var(change), quantile_change = quantile(change), 
    min_change = min(change), max_change = max(change), n_rows = n(), 
    n_dist_change = n_distinct(change)) %&gt;% kable()</code></pre>
<table>
<colgroup>
<col width="13%" />
<col width="10%" />
<col width="11%" />
<col width="17%" />
<col width="11%" />
<col width="11%" />
<col width="7%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">mean_change</th>
<th align="right">sd_change</th>
<th align="right">var_change</th>
<th align="right">quantile_change</th>
<th align="right">min_change</th>
<th align="right">max_change</th>
<th align="right">n_rows</th>
<th align="right">n_dist_change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5.746479</td>
<td align="right">22.50315</td>
<td align="right">506.392</td>
<td align="right">-21.0</td>
<td align="right">-21</td>
<td align="right">158</td>
<td align="right">71</td>
<td align="right">35</td>
</tr>
<tr class="even">
<td align="right">5.746479</td>
<td align="right">22.50315</td>
<td align="right">506.392</td>
<td align="right">-3.5</td>
<td align="right">-21</td>
<td align="right">158</td>
<td align="right">71</td>
<td align="right">35</td>
</tr>
<tr class="odd">
<td align="right">5.746479</td>
<td align="right">22.50315</td>
<td align="right">506.392</td>
<td align="right">2.0</td>
<td align="right">-21</td>
<td align="right">158</td>
<td align="right">71</td>
<td align="right">35</td>
</tr>
<tr class="even">
<td align="right">5.746479</td>
<td align="right">22.50315</td>
<td align="right">506.392</td>
<td align="right">9.0</td>
<td align="right">-21</td>
<td align="right">158</td>
<td align="right">71</td>
<td align="right">35</td>
</tr>
<tr class="odd">
<td align="right">5.746479</td>
<td align="right">22.50315</td>
<td align="right">506.392</td>
<td align="right">158.0</td>
<td align="right">-21</td>
<td align="right">158</td>
<td align="right">71</td>
<td align="right">35</td>
</tr>
</tbody>
</table>
<pre class="r"><code>newjoin2 %&gt;% summarize(mean_murders2015_per_pop = mean(murders2015_per_pop, 
    na.rm = T), sd_murders2015_per_pop = sd(murders2015_per_pop), 
    var_murders2015_per_pop = var(murders2015_per_pop), quantile_murders2015_per_pop = quantile(murders2015_per_pop), 
    min_murders2015_per_pop = min(murders2015_per_pop), max_murders2015_per_pop = max(murders2015_per_pop), 
    n_rows = n(), n_dist_murders2015_per_pop = n_distinct(murders2015_per_pop)) %&gt;% 
    kable()</code></pre>
<table>
<colgroup>
<col width="13%" />
<col width="12%" />
<col width="13%" />
<col width="15%" />
<col width="13%" />
<col width="13%" />
<col width="3%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">mean_murders2015_per_pop</th>
<th align="right">sd_murders2015_per_pop</th>
<th align="right">var_murders2015_per_pop</th>
<th align="right">quantile_murders2015_per_pop</th>
<th align="right">min_murders2015_per_pop</th>
<th align="right">max_murders2015_per_pop</th>
<th align="right">n_rows</th>
<th align="right">n_dist_murders2015_per_pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0002279</td>
<td align="right">0.0004251</td>
<td align="right">2e-07</td>
<td align="right">0.0000000</td>
<td align="right">0</td>
<td align="right">0.0020372</td>
<td align="right">71</td>
<td align="right">70</td>
</tr>
<tr class="even">
<td align="right">0.0002279</td>
<td align="right">0.0004251</td>
<td align="right">2e-07</td>
<td align="right">0.0000396</td>
<td align="right">0</td>
<td align="right">0.0020372</td>
<td align="right">71</td>
<td align="right">70</td>
</tr>
<tr class="odd">
<td align="right">0.0002279</td>
<td align="right">0.0004251</td>
<td align="right">2e-07</td>
<td align="right">0.0000898</td>
<td align="right">0</td>
<td align="right">0.0020372</td>
<td align="right">71</td>
<td align="right">70</td>
</tr>
<tr class="even">
<td align="right">0.0002279</td>
<td align="right">0.0004251</td>
<td align="right">2e-07</td>
<td align="right">0.0001655</td>
<td align="right">0</td>
<td align="right">0.0020372</td>
<td align="right">71</td>
<td align="right">70</td>
</tr>
<tr class="odd">
<td align="right">0.0002279</td>
<td align="right">0.0004251</td>
<td align="right">2e-07</td>
<td align="right">0.0020372</td>
<td align="right">0</td>
<td align="right">0.0020372</td>
<td align="right">71</td>
<td align="right">70</td>
</tr>
</tbody>
</table>
<pre class="r"><code>newjoin2 %&gt;% summarize(mean_murders2016_per_pop = mean(murders2016_per_pop, 
    na.rm = T), sd_murders2016_per_pop = sd(murders2016_per_pop), 
    var_murders2016_per_pop = var(murders2016_per_pop), quantile_murders2016_per_pop = quantile(murders2016_per_pop), 
    min_murders2016_per_pop = min(murders2016_per_pop), max_murders2016_per_pop = max(murders2016_per_pop), 
    n_rows = n(), n_dist_murders2016_per_pop = n_distinct(murders2016_per_pop)) %&gt;% 
    kable()</code></pre>
<table>
<colgroup>
<col width="13%" />
<col width="12%" />
<col width="13%" />
<col width="15%" />
<col width="13%" />
<col width="13%" />
<col width="3%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">mean_murders2016_per_pop</th>
<th align="right">sd_murders2016_per_pop</th>
<th align="right">var_murders2016_per_pop</th>
<th align="right">quantile_murders2016_per_pop</th>
<th align="right">min_murders2016_per_pop</th>
<th align="right">max_murders2016_per_pop</th>
<th align="right">n_rows</th>
<th align="right">n_dist_murders2016_per_pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0002428</td>
<td align="right">0.0004078</td>
<td align="right">2e-07</td>
<td align="right">0.0000117</td>
<td align="right">1.17e-05</td>
<td align="right">0.0018887</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="even">
<td align="right">0.0002428</td>
<td align="right">0.0004078</td>
<td align="right">2e-07</td>
<td align="right">0.0000466</td>
<td align="right">1.17e-05</td>
<td align="right">0.0018887</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="odd">
<td align="right">0.0002428</td>
<td align="right">0.0004078</td>
<td align="right">2e-07</td>
<td align="right">0.0000970</td>
<td align="right">1.17e-05</td>
<td align="right">0.0018887</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="even">
<td align="right">0.0002428</td>
<td align="right">0.0004078</td>
<td align="right">2e-07</td>
<td align="right">0.0002216</td>
<td align="right">1.17e-05</td>
<td align="right">0.0018887</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
<tr class="odd">
<td align="right">0.0002428</td>
<td align="right">0.0004078</td>
<td align="right">2e-07</td>
<td align="right">0.0018887</td>
<td align="right">1.17e-05</td>
<td align="right">0.0018887</td>
<td align="right">71</td>
<td align="right">71</td>
</tr>
</tbody>
</table>
<pre class="r"><code>## SUMMARY STATISTICS WITH GROUPING BY STATE

newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_pop = mean(pop, 
    na.rm = T), sd_pop = sd(pop), var_pop = var(pop), quantile_pop = quantile(pop), 
    min_pop = min(pop), max_pop = max(pop), n_rows = n(), n_dist_pop = n_distinct(pop)) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Rows: 160
## Columns: 9
## Groups: state [32]
## $ state        &lt;chr&gt; &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL…
## $ mean_pop     &lt;dbl&gt; 279428.0, 279428.0, 279428.0, 279428.0, 279428.0, 188467.…
## $ sd_pop       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 629923.8, 629923.…
## $ var_pop      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 396804013504, 396…
## $ quantile_pop &lt;dbl&gt; 279428.0, 279428.0, 279428.0, 279428.0, 279428.0, 188467.…
## $ min_pop      &lt;int&gt; 279428, 279428, 279428, 279428, 279428, 188467, 188467, 1…
## $ max_pop      &lt;int&gt; 279428, 279428, 279428, 279428, 279428, 188467, 188467, 1…
## $ n_rows       &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 9, 9, 9, 9, …
## $ n_dist_pop   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 9, 9, 9, 9, …</code></pre>
<pre class="r"><code>newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_murders2015 = mean(murders_2015, 
    na.rm = T), sd_muders2015 = sd(murders_2015), var_murders2015 = var(murders_2015), 
    quantile_murders2015 = quantile(murders_2015), min_murders2015 = min(murders_2015), 
    max_murders2015 = max(murders_2015), n_rows = n(), n_dist_murders2015 = n_distinct(murders_2015)) %&gt;% 
    glimpse</code></pre>
<pre><code>## Rows: 160
## Columns: 9
## Groups: state [32]
## $ state                &lt;chr&gt; &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;…
## $ mean_murders2015     &lt;dbl&gt; 19.00000, 19.00000, 19.00000, 19.00000, 19.00000,…
## $ sd_muders2015        &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 35.92121,…
## $ var_murders2015      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1290.3333…
## $ quantile_murders2015 &lt;dbl&gt; 19.00, 19.00, 19.00, 19.00, 19.00, 6.00, 6.00, 6.…
## $ min_murders2015      &lt;int&gt; 19, 19, 19, 19, 19, 6, 6, 6, 6, 6, 2, 2, 2, 2, 2,…
## $ max_murders2015      &lt;int&gt; 19, 19, 19, 19, 19, 6, 6, 6, 6, 6, 72, 72, 72, 72…
## $ n_rows               &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 9, 9…
## $ n_dist_murders2015   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 8, 8…</code></pre>
<pre class="r"><code>newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_murders2016 = mean(murders_2016, 
    na.rm = T), sd_muders2016 = sd(murders_2016), var_murders2016 = var(murders_2016), 
    quantile_murders2016 = quantile(murders_2016), min_murders2016 = min(murders_2016), 
    max_murders2016 = max(murders_2016), n_rows = n(), n_dist_murders2016 = n_distinct(murders_2016)) %&gt;% 
    glimpse</code></pre>
<pre><code>## Rows: 160
## Columns: 9
## Groups: state [32]
## $ state                &lt;chr&gt; &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;…
## $ mean_murders2016     &lt;dbl&gt; 26.00000, 26.00000, 26.00000, 26.00000, 26.00000,…
## $ sd_muders2016        &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 58.50641,…
## $ var_murders2016      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3423.0000…
## $ quantile_murders2016 &lt;dbl&gt; 26.00, 26.00, 26.00, 26.00, 26.00, 12.00, 12.00, …
## $ min_murders2016      &lt;int&gt; 26, 26, 26, 26, 26, 12, 12, 12, 12, 12, 3, 3, 3, …
## $ max_murders2016      &lt;int&gt; 26, 26, 26, 26, 26, 12, 12, 12, 12, 12, 111, 111,…
## $ n_rows               &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 9, 9…
## $ n_dist_murders2016   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 9, 9…</code></pre>
<pre class="r"><code>newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_change = mean(change, 
    na.rm = T), sd_change = sd(change), var_change = var(change), 
    quantile_change = quantile(change), min_change = min(change), 
    max_change = max(change), n_rows = n(), n_dist_change = n_distinct(change)) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Rows: 160
## Columns: 9
## Groups: state [32]
## $ state           &lt;chr&gt; &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, …
## $ mean_change     &lt;dbl&gt; 7.000000, 7.000000, 7.000000, 7.000000, 7.000000, 6.00…
## $ sd_change       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 23.860707, 23.…
## $ var_change      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 569.33333, 569…
## $ quantile_change &lt;dbl&gt; 7.0, 7.0, 7.0, 7.0, 7.0, 6.0, 6.0, 6.0, 6.0, 6.0, -5.0…
## $ min_change      &lt;int&gt; 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, -5, -5, -5, -5, -5, -13,…
## $ max_change      &lt;int&gt; 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 39, 39, 39, 39, 39, 9, 9…
## $ n_rows          &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 9, 9, 9, …
## $ n_dist_change   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 8, 8, 8, …</code></pre>
<pre class="r"><code>newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_murders2015_per_pop = mean(murders2015_per_pop, 
    na.rm = T), sd_murders2015_per_pop = sd(murders2015_per_pop), 
    var_murders2015_per_pop = var(murders2015_per_pop), quantile_murders2015_per_pop = quantile(murders2015_per_pop), 
    min_murders2015_per_pop = min(murders2015_per_pop), max_murders2015_per_pop = max(murders2015_per_pop), 
    n_rows = n(), n_dist_murders2015_per_pop = n_distinct(murders2015_per_pop)) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Rows: 160
## Columns: 9
## Groups: state [32]
## $ state                        &lt;chr&gt; &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AL&quot;, &quot;AL&quot;,…
## $ mean_murders2015_per_pop     &lt;dbl&gt; 6.799605e-05, 6.799605e-05, 6.799605e-05,…
## $ sd_murders2015_per_pop       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2…
## $ var_murders2015_per_pop      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5…
## $ quantile_murders2015_per_pop &lt;dbl&gt; 6.799605e-05, 6.799605e-05, 6.799605e-05,…
## $ min_murders2015_per_pop      &lt;dbl&gt; 6.799605e-05, 6.799605e-05, 6.799605e-05,…
## $ max_murders2015_per_pop      &lt;dbl&gt; 6.799605e-05, 6.799605e-05, 6.799605e-05,…
## $ n_rows                       &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3,…
## $ n_dist_murders2015_per_pop   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3,…</code></pre>
<pre class="r"><code>newjoin2 %&gt;% group_by(state) %&gt;% summarize(mean_murders2016_per_pop = mean(murders2016_per_pop, 
    na.rm = T), sd_murders2016_per_pop = sd(murders2016_per_pop), 
    var_murders2016_per_pop = var(murders2016_per_pop), quantile_murders2016_per_pop = quantile(murders2016_per_pop), 
    min_murders2016_per_pop = min(murders2016_per_pop), max_murders2016_per_pop = max(murders2016_per_pop), 
    n_rows = n(), n_dist_murders2016_per_pop = n_distinct(murders2016_per_pop)) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Rows: 160
## Columns: 9
## Groups: state [32]
## $ state                        &lt;chr&gt; &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AK&quot;, &quot;AL&quot;, &quot;AL&quot;,…
## $ mean_murders2016_per_pop     &lt;dbl&gt; 9.304723e-05, 9.304723e-05, 9.304723e-05,…
## $ sd_murders2016_per_pop       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3…
## $ var_murders2016_per_pop      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1…
## $ quantile_murders2016_per_pop &lt;dbl&gt; 9.304723e-05, 9.304723e-05, 9.304723e-05,…
## $ min_murders2016_per_pop      &lt;dbl&gt; 9.304723e-05, 9.304723e-05, 9.304723e-05,…
## $ max_murders2016_per_pop      &lt;dbl&gt; 9.304723e-05, 9.304723e-05, 9.304723e-05,…
## $ n_rows                       &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3,…
## $ n_dist_murders2016_per_pop   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3,…</code></pre>
<pre class="r"><code>newjoin2 %&gt;% group_by(state, capital) %&gt;% summarize(mean_pop = mean(pop, 
    na.rm = T), sd_pop = sd(pop), var_pop = var(pop), min_pop = min(pop), 
    max_pop = max(pop), n_rows = n(), n_dist_pop = n_distinct(pop)) %&gt;% 
    glimpse()</code></pre>
<pre><code>## Rows: 43
## Columns: 9
## Groups: state [32]
## $ state      &lt;chr&gt; &quot;AK&quot;, &quot;AL&quot;, &quot;AZ&quot;, &quot;AZ&quot;, &quot;CA&quot;, &quot;CA&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;FL&quot;, &quot;GA&quot;,…
## $ capital    &lt;chr&gt; &quot;Non-capital&quot;, &quot;Non-capital&quot;, &quot;Non-capital&quot;, &quot;State-capital…
## $ mean_pop   &lt;dbl&gt; 279428.0, 188467.0, 386591.5, 1450884.0, 274024.4, 480392.0…
## $ sd_pop     &lt;dbl&gt; NA, NA, 196118.19, NA, 154742.08, NA, NA, NA, 314942.31, NA…
## $ var_pop    &lt;dbl&gt; NA, NA, 3.846234e+10, NA, 2.394511e+10, NA, NA, NA, 9.91886…
## $ min_pop    &lt;int&gt; 279428, 188467, 247915, 1450884, 40805, 480392, 304641, 556…
## $ max_pop    &lt;int&gt; 279428, 188467, 525268, 1450884, 472517, 480392, 304641, 55…
## $ n_rows     &lt;int&gt; 1, 1, 2, 1, 8, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 1,…
## $ n_dist_pop &lt;int&gt; 1, 1, 2, 1, 8, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 1,…</code></pre>
<pre class="r"><code>newjoin2cormat &lt;- newjoin2 %&gt;% select_if(is.numeric) %&gt;% cor(use = &quot;pair&quot;)
kable(newjoin2cormat)</code></pre>
<table>
<colgroup>
<col width="18%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">pop</th>
<th align="right">murders_2015</th>
<th align="right">murders_2016</th>
<th align="right">change</th>
<th align="right">murders2015_per_pop</th>
<th align="right">murders2016_per_pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">pop</td>
<td align="right">1.0000000</td>
<td align="right">0.7451756</td>
<td align="right">0.8005471</td>
<td align="right">0.6362003</td>
<td align="right">-0.2497521</td>
<td align="right">-0.2642073</td>
</tr>
<tr class="even">
<td align="left">murders_2015</td>
<td align="right">0.7451756</td>
<td align="right">1.0000000</td>
<td align="right">0.9678577</td>
<td align="right">0.4831888</td>
<td align="right">0.2054960</td>
<td align="right">0.1897713</td>
</tr>
<tr class="odd">
<td align="left">murders_2016</td>
<td align="right">0.8005471</td>
<td align="right">0.9678577</td>
<td align="right">1.0000000</td>
<td align="right">0.6878489</td>
<td align="right">0.1343065</td>
<td align="right">0.1421998</td>
</tr>
<tr class="even">
<td align="left">change</td>
<td align="right">0.6362003</td>
<td align="right">0.4831888</td>
<td align="right">0.6878489</td>
<td align="right">1.0000000</td>
<td align="right">-0.1255376</td>
<td align="right">-0.0526764</td>
</tr>
<tr class="odd">
<td align="left">murders2015_per_pop</td>
<td align="right">-0.2497521</td>
<td align="right">0.2054960</td>
<td align="right">0.1343065</td>
<td align="right">-0.1255376</td>
<td align="right">1.0000000</td>
<td align="right">0.9838140</td>
</tr>
<tr class="even">
<td align="left">murders2016_per_pop</td>
<td align="right">-0.2642073</td>
<td align="right">0.1897713</td>
<td align="right">0.1421998</td>
<td align="right">-0.0526764</td>
<td align="right">0.9838140</td>
<td align="right">1.0000000</td>
</tr>
</tbody>
</table>
<p><span style="color:blue">First all 6 dplyr functions were used to analyze the data. The “filter” function was used to filter and view the dataset with only cities in Texas. The “select” function was used to permanently remove the rows “state.x” and “state.y”, which were repeats of the column “country.etc”, and also to remove the rows “source”, “as_of”, “lat” and “long”. The “rename” function was used to change the column title “country.etc” to “state”. The “arrange” function was first used to arrange cities by most to least number of murders in 2015. It can be seen that Chicago had the greatest number of 2015 murders. By using “group_by” to group by state, then using “summarize” to find the mean murders in 2015 of each state, and finally using arrange to arrange the mean 2015 murders from greatest to least, it can be seen that Maryland has the greatest average murders in 2015, followed by Michigan and Pennsylvania. Using the same functions, I arranged the states by greatest to least mean population size. Michigan, Pennsylvania and Illinois had the greatest average population. Suprisingly, Maryland, which had the greatest mean murders in 2015, was not among the top 5 most populous states. This goes against my prediction that greater population would correlate with a greater number of murders. I then used the “mutate” function to create the new variables “murders2015_per_pop” and “murders2016_per_pop”, which describe the number of murders as a proportion of each city’s population. By using the “group_by”, “summarize” and "arrange functions, I found that Indiana had the greatest average murders per person in 2015, followed by Ohio and Maryland</span>.</p>
<p><span style="color:blue">I then computed the summary statistics of each numeric variable, using the “mean”, “sd”, “var”, “quantile”, “min”, “max”, “n” and “n_distinct” functions within the “summarize” function. I laid these statistics out in a table using the “kable” function. I followed the same procedure to compute the summary statistics after grouping by state. Not suprisingly, there were very large standard deviations and variances for each of the variables, which makes sense given the variability of city statistics. The exception to this came when grouping by state and recieving “NA” for the standard devation and variance of some states, such as Arkansas. This was because some states were only represented by 1 city in this dataset and therefore there was no standard deviation/variability within that state’s data. I also grouped by both state and capital status, and computed population statistics. For all states having capital and non-capital cities, except for Tennesee, the capital city had a greater mean population compared to the state’s non-captial cities. Lastly, I created a correlation matrix of my numeric variables, called “newjoin2cormat”</span>.</p>
</div>
<div id="visualizing" class="section level3">
<h3>Visualizing</h3>
<div id="heat-map" class="section level4">
<h4>Heat Map</h4>
<pre class="r"><code>library(tibble)
tidycor &lt;- newjoin2cormat %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% 
    pivot_longer(-1, names_to = &quot;var2&quot;, values_to = &quot;correlation&quot;)

tidycor %&gt;% arrange(desc(correlation))</code></pre>
<pre><code>## # A tibble: 36 x 3
##    var1                var2                correlation
##    &lt;chr&gt;               &lt;chr&gt;                     &lt;dbl&gt;
##  1 pop                 pop                       1    
##  2 murders_2015        murders_2015              1    
##  3 murders_2016        murders_2016              1    
##  4 change              change                    1    
##  5 murders2015_per_pop murders2015_per_pop       1    
##  6 murders2016_per_pop murders2016_per_pop       1    
##  7 murders2015_per_pop murders2016_per_pop       0.984
##  8 murders2016_per_pop murders2015_per_pop       0.984
##  9 murders_2015        murders_2016              0.968
## 10 murders_2016        murders_2015              0.968
## # … with 26 more rows</code></pre>
<pre class="r"><code>library(ggplot2)
tidycor %&gt;% ggplot(aes(var1, var2, fill = correlation)) + geom_tile() + 
    ggtitle(&quot;Heat Map of Numeric Variables&quot;) + scale_fill_gradient2(low = &quot;green&quot;, 
    mid = &quot;yellow&quot;, high = &quot;red&quot;) + geom_text(aes(label = round(correlation, 
    2)), color = &quot;black&quot;, size = 4) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="plot-type-1-scatterplot" class="section level4">
<h4>Plot Type #1: Scatterplot</h4>
<pre class="r"><code>newjoin2 %&gt;% ggplot(aes(murders_2015, pop, color = capital)) + 
    geom_point() + ggtitle(&quot;Population vs. Number of 2015 Murders in Capital and Non-Capital Cities&quot;) + 
    xlab(&quot;Number of Murders in 2015&quot;) + ylab(&quot;City Population&quot;) + 
    scale_x_log10(labels = scales::number, n.breaks = 7) + scale_y_log10(labels = scales::number, 
    n.breaks = 7) + geom_smooth(method = &quot;lm&quot;, formula = y ~ 
    x, colour = &quot;red&quot;) + theme_light()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>newjoin2 %&gt;% ggplot(aes(murders_2016, pop, color = capital)) + 
    geom_point() + ggtitle(&quot;Population vs. Number of 2016 Murders in Capital and Non-Capital Cities&quot;) + 
    xlab(&quot;Number of Murders in 2016&quot;) + ylab(&quot;City Population&quot;) + 
    scale_x_log10(labels = scales::number, n.breaks = 7) + scale_y_log10(labels = scales::number, 
    n.breaks = 7) + geom_smooth(method = &quot;lm&quot;, formula = y ~ 
    x, colour = &quot;red&quot;) + theme_light()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-2.png" width="672" style="display: block; margin: auto;" />
<span style="color:blue">For my first set of plots, I decided to use a scatterplot to look at the number of murders in 2015/2016 versus the population size of each city. The color of the points are colored based on whether the city was a capital or non-captial city. To further evaluate the relationship between city population and the number of 2015/2016 murders, I fitted a linear regression line to the points. Looking at this regression line, it can be seen that there is a slight, positive linear relationship between the population size and the number of murders in a city.When focusing on the capital status of the cities, it can be seen that capital cities tend to have a higher city population. On the other hand however, capital-status does not appear to have any effect on the number of murders</span>.</p>
</div>
<div id="plot-type-2-grouped-barplot" class="section level4">
<h4>Plot Type #2: Grouped Barplot</h4>
<pre class="r"><code>newjoin2 %&gt;% ggplot(aes(x = state, y = murders_2015, fill = capital)) + 
    geom_bar(position = &quot;dodge&quot;, stat = &quot;summary&quot;) + ggtitle(&quot;State vs. Number of 2015 Murders in Capital and Non-Capital Cities&quot;) + 
    ylab(&quot;Number of Murders in 2015&quot;) + xlab(&quot;State&quot;) + scale_fill_brewer(palette = &quot;Set2&quot;) + 
    theme_dark()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>newjoin2 %&gt;% ggplot(aes(x = state, y = murders_2016, fill = capital)) + 
    geom_bar(position = &quot;dodge&quot;, stat = &quot;summary&quot;) + ggtitle(&quot;State vs. Number of 2016 Murders in Capital and Non-Capital Cities&quot;) + 
    ylab(&quot;Number of Murders in 2016&quot;) + xlab(&quot;State&quot;) + scale_fill_brewer(palette = &quot;Set3&quot;) + 
    theme_dark()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-7-2.png" width="672" style="display: block; margin: auto;" />
<span style="color:blue">The second set of variables I decided to look at were state, number of 2015/2016 murders and capital status. I placed these variables on a grouped bar plot, where I could see the average number of 2015/2016 murders for the capital and non-capital cities of each state. Average number of murders was computed using the “stat=summary” function. By looking at both the 2015 and 2016 plots, it can be seen that the highest average number of murders occured in Maine and Michigan for both years. For states represented by both capital and non-capital cities, it appears that the average number of murders is independent of whether the city is a capital city or non-capital city. This supports what was found from the scatterplots of city population, number of murders and capital status</span>.</p>
</div>
</div>
<div id="dimensionality" class="section level3">
<h3>Dimensionality</h3>
<pre class="r"><code>library(tidyverse)
library(cluster)

gowdat &lt;- newjoin2 %&gt;% select(city, pop, murders_2015, murders_2016, 
    change) %&gt;% mutate_if(is.character, as.factor)
gower1 &lt;- daisy(gowdat, metric = &quot;gower&quot;)

sil_width &lt;- vector()
for (i in 2:10) {
    pam_fit &lt;- pam(gower1, diss = TRUE, k = i)
    sil_width[i] &lt;- pam_fit$silinfo$avg.width
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>pam1 &lt;- pam(gower1, k = 2, diss = T)
pam1</code></pre>
<pre><code>## Medoids:
##      ID        
## [1,] &quot;6&quot;  &quot;35&quot; 
## [2,] &quot;50&quot; &quot;613&quot;
## Clustering vector:
##   7  20  21  33  34  35  36  41  48  49  50  53  55  98 125 126 161 173 180 184 
##   1   1   1   1   1   1   1   2   1   1   1   1   2   1   1   1   1   2   2   2 
## 185 197 198 199 225 247 250 260 337 368 395 411 413 422 432 433 486 504 506 507 
##   2   2   2   2   2   1   2   1   1   1   1   1   2   2   2   2   1   1   1   1 
## 522 549 558 559 567 568 576 601 612 613 614 642 650 655 693 694 701 705 720 721 
##   2   2   2   2   2   1   1   2   2   2   2   2   1   1   2   2   2   1   1   1 
## 732 756 778 833 834 873 907 919 921 987 988 
##   1   1   1   1   1   1   1   1   1   1   1 
## Objective function:
##     build      swap 
## 0.2434865 0.2389481 
## 
## Available components:
## [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
## [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;</code></pre>
<pre class="r"><code>pam1$silinfo$avg.width</code></pre>
<pre><code>## [1] 0.1745174</code></pre>
<pre class="r"><code>library(Rtsne)
tsne_obj &lt;- Rtsne(gower1, is_distance = TRUE, perplexity = 2)
tsne_data &lt;- tsne_obj$Y %&gt;% data.frame() %&gt;% setNames(c(&quot;X&quot;, 
    &quot;Y&quot;)) %&gt;% mutate(cluster = factor(pam1$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) + geom_point(aes(color = cluster))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-8-2.png" width="672" style="display: block; margin: auto;" /></p>
<p><span style="color:blue">Since I wanted to evaluate both numeric and categorical data, I used gower dissimilarities for my PAM clustering. First, I grabbed the variables I wanted to use in my cluster using the “select” function and turned any characters into factors using the “mutate_if” function. I named this new dataset “gowdat”. I then computed the gower distances using the “daisy” function and created a vector called “gower1”. I ran the “pam” function on these gower dissimilarities to find the ideal number of clusters for running PAM. The ideal number of clusters was 2 becuase had the highest highest average silhouette width, which gives the most separated and most cohesive clusters. PAM was then run using 2 clusters. Silhouette width was found to be 0.175 and because this was less than 0.25, this means that no substantial structure was found. This is expected given the results of the plots and correlation matrix found previously. Finally, I created a visualization of the clusters using the “Rtsne” and “ggplot” functions. In this plot, it can be seen that the clusters are not very separated </span>.</p>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
